Starting script...
Traceback (most recent call last):
  File "C:\Users\nehad\PycharmProjects\MetropolisWebInterfacebatch\batchtest\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\nehad\PycharmProjects\MetropolisWebInterfacebatch\batchtest\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\nehad\PycharmProjects\MetropolisWebInterfacebatch\batchtest\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "C:\Users\nehad\PycharmProjects\MetropolisWebInterfacebatch\batchtest\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "C:\Users\nehad\PycharmProjects\MetropolisWebInterfacebatch\batchtest\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`metropolis_batch`.`batchrun`, CONSTRAINT `BatchRun_batch_id_18abf2ab_fk_Batch_id` FOREIGN KEY (`batch_id`) REFERENCES `batch` (`id`))')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\nehad\PycharmProjects\MetropolisWebInterfacebatch/metro_app/batch_run.py", line 65, in <module>
    batch_run.save()
  File "C:\Users\nehad\PycharmProjects\MetropolisWebInterfacebatch\batchtest\lib\site-packages\django\db\models\base.py", line 753, in save
    self.save_base(using=using, force_insert=force_insert,
  File "C:\Users\nehad\PycharmProjects\MetropolisWebInterfacebatch\batchtest\lib\site-packages\django\db\models\base.py", line 790, in save_base
    updated = self._save_table(
  File "C:\Users\nehad\PycharmProjects\MetropolisWebInterfacebatch\batchtest\lib\site-packages\django\db\models\base.py", line 895, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "C:\Users\nehad\PycharmProjects\MetropolisWebInterfacebatch\batchtest\lib\site-packages\django\db\models\base.py", line 933, in _do_insert
    return manager._insert(
  File "C:\Users\nehad\PycharmProjects\MetropolisWebInterfacebatch\batchtest\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\nehad\PycharmProjects\MetropolisWebInterfacebatch\batchtest\lib\site-packages\django\db\models\query.py", line 1254, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Users\nehad\PycharmProjects\MetropolisWebInterfacebatch\batchtest\lib\site-packages\django\db\models\sql\compiler.py", line 1397, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\nehad\PycharmProjects\MetropolisWebInterfacebatch\batchtest\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "C:\Users\nehad\PycharmProjects\MetropolisWebInterfacebatch\batchtest\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\nehad\PycharmProjects\MetropolisWebInterfacebatch\batchtest\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\nehad\PycharmProjects\MetropolisWebInterfacebatch\batchtest\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\nehad\PycharmProjects\MetropolisWebInterfacebatch\batchtest\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\nehad\PycharmProjects\MetropolisWebInterfacebatch\batchtest\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\nehad\PycharmProjects\MetropolisWebInterfacebatch\batchtest\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\nehad\PycharmProjects\MetropolisWebInterfacebatch\batchtest\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "C:\Users\nehad\PycharmProjects\MetropolisWebInterfacebatch\batchtest\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "C:\Users\nehad\PycharmProjects\MetropolisWebInterfacebatch\batchtest\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`metropolis_batch`.`batchrun`, CONSTRAINT `BatchRun_batch_id_18abf2ab_fk_Batch_id` FOREIGN KEY (`batch_id`) REFERENCES `batch` (`id`))')
